### PR TITLE
Prevent default browser-supplied validation bubbles

### PR DESCRIPTION
**Pull request by mdulat**
... same as for text-input https://github.com/BrightspaceUI/text-input/pull/18

### CODE REVIEW

**Comment by dbatiste** [comment]
How are validation messages being presented in the app (without these)?

**Comment by mdulat** [comment]
For Rubrics we are using d2l-tooltip to display an error bubble (see attached screenshot), but I'm not sure what other users of this component do. It's probably better to pass an argument indicating whether or not to suppress the default behaviour, what do you think?
errorbubble

**Comment by dlockhart** [comment]
So the correct thing we should be doing is figuring out how to integrate validation errors into our input web components -- textareas, text inputs, etc. But that's a larger endeavour.

**Comment by mdulat** [comment]
Agreed. There does appear to be a way to customize the text within the default bubble, but no way to custom style it. I guess a question for designers, but might we want to use these default bubbles across Brightspace? If not, we'll need to scrap the default behaviour even if we implement a validation solution within these components. Would be nice to have these standardized. 

In the mean time, do we scrap these defaults?

**Comment by mdulat** [comment]
Great, are these OK to merge like this then?

**Comment by dbatiste** [comment]
Yep, I think so.

**Pull request merged**
